version = 1
SPDX-PackageName = "github-data"
SPDX-PackageSupplier = "Person: Stoney Jackson <dr.stoney@gmail.com>"
SPDX-PackageDownloadLocation = "NOASSERTION"

[[annotations]]
path = ["**"]
precedence = "closest"
SPDX-FileCopyrightText = "2025 Stoney Jackson <dr.stoney@gmail.com>"
SPDX-License-Identifier = "MIT"